### PR TITLE
docs: Examples

### PR DESCRIPTION
**Pull request by raghanag**
## Description

Adds the mocha, chai, typescript with puppeteer example

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] My code follows the code style of this project.
- [ ] My commits and the title of this PR follow the [Conventional Commits Specification](https://www.conventionalcommits.org).
- [x] I have read the [contributing guidelines](https://github.com/Netflix/pollyjs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by raghanag** [comment]
Hi, @jasonmit I took the liberty to add ts-mocha example, but it has many flaws. For example, 

- in this example, if I didn't mention slowMo: 1000 while launching a browser, the tests are failing.

- If I mention whatever is in beforeEach in describe, the tests are failing. maybe a mocha expert can debug.

- page.$$('a.MenuItemLink-root-243') this is wrong, but I didn't find a way to find the links just like the jest toClick method in mocha/chai.

Please let me know if it's relevant to add the ts-mocha example.

**Comment by raghanag** [comment]
HI @wesleytodd Can you please take a look at my issues I mentioned above.

**Comment by wesleytodd** [comment]
Hi, I am not sure why I am being pinged on this.  I am happy to take a look if there is a reason, but I have never contributed to this project.

**Comment by raghanag** [comment]
Sorry to tag you, I was told on Gitter community that you can help me with Mocha. I am trying to contribute a mocha, typescript, puppeteer pollyjs example.

**Comment by wesleytodd** [comment]
I also don't contribute to any of those projects.  I use mocha, but wont be much help beyond what any average user would know.  Good luck with your project! Sorry I can't be more help.

**Comment by jasonmit** [comment]
I don't believe there's a desire on our end to support this very specific configuration.  It's already difficult for us to keep the current examples up to date with the rest of the library as we're not currently testing them.

**Pull request closed without merging**
