### PR TITLE
feat: Simplify PuppeteerAdapter to avoid creating duplicate requests

### PR DESCRIPTION
**Pull request by lguychard**
## Description

Simplifies the PuppeteerAdapter to avoid creating "duplicate" requests for passthrough requests with a `pollyjs_passthrough_req_id` query parameter. This is changed to simply call `.continue()` on passthrough requests.

This also fixes the hanging issue when including `document` in `requestResourceTypes` (https://github.com/Netflix/pollyjs/issues/121#issue-374093084)

## Motivation and Context

I wanted to be able to record the initial `document` using the PuppeteerAdapter. I noticed that the reason this was not possible was that the `fetch()` request constructed by the adapter hung after receiving an `OPTIONS` response when requesting the initial document. I investigated removing these `fetch()` calls, and simply calling `request.continue()`, which would remove the hanging problem, and simplify the internal implementation.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have added tests to cover my changes ([relevant tests pass](https://travis-ci.org/github/Netflix/pollyjs/jobs/704355655#L1280-L1296), the functionality of the Puppeteer adapter is otherwise preserved).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] My code follows the code style of this project.
- [x] My commits and the title of this PR follow the [Conventional Commits Specification](https://www.conventionalcommits.org).
- [x] I have read the [contributing guidelines](https://github.com/Netflix/pollyjs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by offirgolan** [comment]
@lguychard thank you for taking the time to work on this PR.

Unfortunately, the 2nd request with the `PASSTHROUGH_REQ_ID_QP` query parameter is necessary since we don't want to respond to the original request until the polly instance is done interacting with it. Since the request and response can be modified at anytime during the lifecycle of the request via the supported events or full interception, we can't just `continue` the original request.

To be honest, the entire adapter needs to be rethought out because of #345 as well as some other issues we've seen with xhr vs fetch requests.

**Comment by lguychard** [comment]
Thanks for taking a look @offirgolan 

> full interception

 As far as full interception goes, this PR leaves the existing functionality unchanged AFAICT.

> the request and response can be modified at anytime during the lifecycle of the request

This is indeed a use case I had overlooked, thanks for pointing it out! Correct me if I'm wrong, but it seems like this would specifically apply to `beforeResponse` and `response` events.

A possible path forward there would be to use the devtools protocol's [`Fetch` API](https://chromedevtools.github.io/devtools-protocol/tot/Fetch). There is previous art at https://github.com/jsoverson/puppeteer-interceptor, and this would still allow to `continue()` the original request and to avoid issuing a separate `fetch()` request.

**Comment by offirgolan** [comment]
> Correct me if I'm wrong, but it seems like this would specifically apply to beforeResponse and response events.

Correct. The `request` event can also modify the final outgoing request to be made (e.g. changing query params or post body).

> A possible path forward there would be to use the devtools protocol's Fetch API. 

That would be great. I wonder if we can use jsoverson/puppeteer-interceptor directly to handle all the interception logic.

**Comment by lguychard** [comment]
Closing this as it won't be merged as-is. We (Sourcegraph) are working internally on a new adapter using CDP Fetch, and will upstream it when it's ready (cc @marekweb).

**Comment by offirgolan** [comment]
That's really awesome to hear! Please don't hesitate to reach out if you need some eyes on it.

**Comment by felixfbecker** [comment]
Thanks for the offer @offirgolan! The PR is here: https://github.com/sourcegraph/sourcegraph/pull/13870, would love to get your review!

**Pull request closed without merging**
