### PR TITLE
[@pollyjs/ember] Fix root path for config and recordings

### PR DESCRIPTION
**Pull request by nfc036**
See https://github.com/Netflix/pollyjs/issues/297#issue-554225908 for a description of the problem.

### CODE REVIEW

**Comment by jasonmit** [comment]
FYI This will reintroduce https://github.com/Netflix/pollyjs/issues/276

**Comment by nfc036** [comment]
Based on https://ember-cli.com/api/classes/Addon.html#props_root this.root is the root of the addon (./node_modules/@pollyjs/ember). Currently the addon is looking for config/polly.js there (in its own root) and it is storing the recordings there too. 

Wasn't #276 related to the use of the included() function? This function is not re-introduced by the supposed change.

**Comment by jasonmit** [comment]
`this.project` is undefined if you run the scenario in #276 on top of your changes.

**Comment by jasonmit** [comment]
https://github.com/Netflix/pollyjs/pull/299 should resolve this without reintroducing #276

Thanks for bringing this to our attention.

**Pull request closed without merging**
