### PR TITLE
docs: added dark mode using docsify-dark-mode

### PR DESCRIPTION
**Pull request by anikethsaha**
## Description

Added dark mode for docs using `docsify-dark-mode` plugin

## Motivation and Context

Better readability

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] docs 

## Checklist

- [ ] I have added tests to cover my changes. : `Not required`
- [ ] My change requires a change to the documentation. `Not required`
- [ ] I have updated the documentation accordingly. `Not required`
- [X] My code follows the code style of this project.
- [X] My commits and the title of this PR follow the [Conventional Commits Specification](https://www.conventionalcommits.org).
- [ X I have read the [contributing guidelines](https://github.com/Netflix/pollyjs/blob/master/CONTRIBUTING.md).

_I have added `Not required` instead of `[X]` as I couldn't find it fitting there, do let me know if this is needed to be changed`_

Screen shot of docs after dark mode

image

image

`Mobile view`

image

image

### CODE REVIEW

**Comment by jasonmit** [comment]
I like it!  Before this lands we need to fix things like the black text in the logo image and the grey subtext should be a bit lighter.

**Comment by anikethsaha** [comment]
> I like it! Before this lands we need to fix things like the black text in the logo image and the grey subtext should be a bit lighter.

cool, it will be solved using config for dark mode. if not, I will add custom css then ! 👍

**Comment by jasonmit** [comment]
@offirgolan do we have the svg file for the logo?

**Comment by offirgolan** [comment]
I like it as well but as @jasonmit said, there are a few things that need to be fixed. 

- A different logo with white text should be used in dark mode, I'll reach out to our designer to get that asset. 
- The text color for the headers and sidebar links should be a much lighter color
- It looks like for the light theme, the text color was changed to red instead of the current black color. 
- The position of the toggle isn't the greatest. Can it be placed next to the hamburger icon instead or at least on the same line?

**Comment by anikethsaha** [comment]
> I like it as well but as @jasonmit said, there are a few things that need to be fixed.
> 
> * A different logo with white text should be used in dark mode, I'll reach out to our designer to get that asset.
> * The text color for the headers and sidebar links should be a much lighter color
> * It looks like for the light theme, the text color was changed to red instead of the current black color.
> * The position of the toggle isn't the greatest. Can it be placed next to the hamburger icon instead or at least on the same line?

Ok , I will try to refactore accordingly 👍

**Comment by jasonmit** [comment]
Ping @anikethsaha

**Comment by anikethsaha** [comment]
sorry for the delay, I know it's being nearly one month since it is open.  I will take a look in this week for sure 👍

**Pull request closed without merging**
