### PR TITLE
fix(core): Strict null query param handling

### LINKED ISSUE #301: `normalize-request` function `url` is manipulating the url and breaking the request
## Description

`@pollyjs/core/src/utils/normalize-request` function `url` is manipulating the url and breaking the request.

When query parameter does not have a value, the function `url` appends a `=`  before making the request. Specifically consuming a WSDL endpoint for a SOAP client does not work because the request url is changed from `?WSDL` to be `?WSDL=`

### Shareable Source

```
index 029eb01..e8e94a3 100644
--- a/packages/@pollyjs/core/tests/unit/utils/normalize-request-test.js
+++ b/packages/@pollyjs/core/tests/unit/utils/normalize-request-test.js
@@ -124,6 +124,10 @@ describe('Unit | Utils | Normalize Request', function() {
       );
     });
 
+    it('should allow WSDL param', function() {
+      expect(url('http://foo.com?WSDL', {})).to.equal('http://foo.com?WSDL');
+    });
+
     it('should respect `matchRequestsBy.url` config', function() {
       [
         [
```

### Error Message & Stack Trace

```
  1) @pollyjs/core
       Unit | Utils | Normalize Request
         url
           should allow WSDL param:

      AssertionError: expected 'http://foo.com?WSDL=' to equal 'http://foo.com?WSDL'
      + expected - actual

      -http://foo.com?WSDL=
      +http://foo.com?WSDL
      
      at Context.<anonymous> (packages/@pollyjs/core/build/node/test-bundle.cjs.js:8305:49)
      at processImmediate (internal/timers.js:439:21)



error Command failed with exit code 1.
```

### Dependencies

Was using the source from this repo @ `v4.0.1`
https://github.com/Netflix/pollyjs/tree/v4.0.1

## Relevant Links

In this instance, I was trying to use https://www.npmjs.com/package/soap

## Environment

```
darwin 18.7.0
Node.js v12.14.1
yarn 1.21.1
```

### PR DESCRIPTION
**Pull request by offirgolan**
## Description

This helps differentiated between `?foo` and `?foo=` query params. 

## Motivation and Context

Resolves #301.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] My code follows the code style of this project.
- [x] My commits and the title of this PR follow the [Conventional Commits Specification](https://www.conventionalcommits.org).
- [x] I have read the [contributing guidelines](https://github.com/Netflix/pollyjs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by offirgolan** [comment]
@jasonmit my only concern here is that this will generate new request ids. Not sure if this warrants being labeled as a breaking change or not.

**Comment by jasonmit** [comment]
I'd say bugfix.  It don't believe it will impact too many, let me know if my assumption is wrong

**Comment by zachawilson** [comment]
Linking to the qs documentation: https://github.com/ljharb/qs#handling-of-null-values

**Comment by offirgolan** [comment]
Release with `v4.0.2`.

**Comment by zachawilson** [comment]
Thank you this is working for us now with `v4.0.2`

**Pull request merged**
